### ISSUE TITLE
inaccurate answer and possible bug not redering answer properly

### ISSUE THREAD

**Issue by jnordwick** [warpdotdev/workflows#104]
### Is this a new workflow or an update?

Update

### What is the name of the workflow?

Find all files in a directory that don't contain a string

### What should the workflow do?

find ALL files

### What does it do (only if it's an update)?

find only files not starting with dot

**Comment by QuentinMoss** [comment]
I believe this was fixed on the preview build as I was unable to reproduce, so should make its way to main build soon.

**Comment by dannyneira** [comment]
@jnordwick Are you still seeing the same issue with the workflow?

**Comment by alokedesai** [comment]
@jnordwick friendly ping on this! Would love to close this out if you are unable to repro

**Comment by jnordwick** [comment]
I'm sorry I wouldn't know I haven't tried this in a while. But please feel
free to close it out Don't keep it open for me

**Comment by alokedesai** [comment]
Great, i'll go ahead and close this out. Please reopen if you start experiencing this issue again!

**Comment by jnordwick** [comment]
I might install this again just check it out watch out Make sure chat GPT
doesn't eat your lunch
