### ISSUE TITLE
osx, workflows and command search panels dont show

### ISSUE THREAD

**Issue by gsiawGH** [warpdotdev/workflows#123]
### What section of this project is the bug in?

Workflows

### What is the bug?

workflows and command search panels dont show if you switch to different shell

### What is the expected behavior?

i start the tab in zsh, and when i press control-shift-R or control-R, the panels pop up, but if i switch/launch any other shell (bash or fish), the same shortcuts do not show the pop up panels

### What is the actual behavior?

 if i switch/launch any other shell (bash or fish), the same shortcuts do not show the pop up panels

### How would you replicate this bug?

start new tab with zsh, switch to bash, press control-shift-R or control-R and nothing shows up, and the menu options under View menu are grayed out

**Comment by gsiawGH** [comment]
i launch zsh to set up environment variables for XDG, which fishshell picks up. but then i can't use workflows

**Comment by alokedesai** [comment]
Hey @gsiawGH, thanks for filing! I'm going to close this out in favor of https://github.com/warpdotdev/Warp/issues/64. My understanding of the issue you are experiencing is that we do not support subshells, so you aren't getting any of the warp features
