### ISSUE TITLE
Workflow param suggestions

### ISSUE THREAD

**Issue by vortechron** [warpdotdev/workflows#130]
### What section of this project is the bug in?

Workflows

### What is the bug?

Feature request / missing feature

### What is the expected behavior?

Workflow param/args can suggest list of option from previous command, example: i run kubectl get pods, and the next workflow command i want to autocomplete/suggest the pod name based on previous command.

### What is the actual behavior?

N/A

### How would you replicate this bug?

N/A

**Comment by elviskahoro** [comment]
@vortechron
I opened a new version of your issue in the Warp repo. Closing this in favor of that one!
https://github.com/warpdotdev/Warp/issues/3015
