### ISSUE TITLE
Broken link: remove_local_branches_not_in_remote

### ISSUE THREAD

**Issue by tylermumford** [warpdotdev/workflows#137]
### What section of this project is the bug in?

Workflows

### What is the bug?

The link to a particular workflow in search results is broken

### What is the expected behavior?

One result, which links to the workflow's page

### What is the actual behavior?

One result, but the link (https://www.commands.dev/workflows/remove_local_branches_not_in_remote) is 404 Not Found

### How would you replicate this bug?

Search commands.dev for "remove all local branches" and click on the only result

**Comment by elviskahoro** [comment]
The url is working now! Apologies. I think the website was down when this was opened.
