### ISSUE TITLE
Laravel migrations

### ISSUE THREAD

**Issue by BurtDS** [warpdotdev/workflows#145]
### Is this a new workflow or an update?

New

### What is the name of the workflow?

laravel migrate

### What should the workflow do?

All the migration things like migrate, with fresh, seed and pretend

**Comment by redaoutamra** [comment]
migrate with fresh will drop all tables and re-migrete again 
migrate with seed is seeding data into the tables after migrating
pretend is used if you want to see the desired result without actually executing the migrate command

**Comment by BurtDS** [comment]
I've added this functionality in PR https://github.com/warpdotdev/workflows/pull/146
