### ISSUE TITLE
Update all pip3 packages Workflow is Incorrect

### ISSUE THREAD

**Issue by csaper** [warpdotdev/workflows#149]
### What section of this project is the bug in?

Workflows

### What is the bug?

The current workflow `pip3 list --outdated --format=freeze | cut -d = -f 1 | xargs -n1 pip3 install -U` results in `ERROR: List format 'freeze' can not be used with the --outdated option.`

### What is the expected behavior?

The correct behavior would be a successful update of the currently installed.  pip packages.

**It seems like the correct command would be:
`pip3 list --outdated --format=columns | tail -n +3 | awk '{print $1}' | xargs -n1 pip3 install -U`**

### What is the actual behavior?

Running the workflow results in an error prior to initiating the package updates.

### How would you replicate this bug?

Open the workflow panel, search for `pip`, select the `Update all pip3 packages` command, and press Enter.

**Comment by alokedesai** [comment]
Hey @csaper, thanks for filing! Can you add more information into the issue about what the problem with the workflow is? Thanks!

**Comment by csaper** [comment]
Sorry @alokedesai -- fat fingers (prematurely submitted the issue with ⌘ + ↵). Now you should see more details in the bug report. Thanks!

**Comment by alokedesai** [comment]
No worries, thank you for clarifying!!

**Comment by elviskahoro** [comment]
@csaper fixed here:
https://github.com/warpdotdev/workflows/commit/c02d2c8245a87f4ce8e47c908a754f2b6fd183c7
