### ISSUE TITLE
Identical workflows for copying files between host and container?

### ISSUE THREAD

**Issue by wzzrd** [warpdotdev/workflows#27]
The workflows to [copy a file from a docker container to the current host](https://github.com/warpdotdev/workflows/blob/main/specs/docker/copy_a_file_from_a_docker_container_to_the_current_host.yaml) and to [copy a file from a host to a container](https://github.com/warpdotdev/workflows/blob/main/specs/docker/copy_files_from_a_host_to_a_docker_container.yaml) seem identical? I haven't used docker in a bit, but I think the 

My guess is [this one](https://github.com/warpdotdev/workflows/blob/main/specs/docker/copy_files_from_a_host_to_a_docker_container.yaml) is the wrong way around and needs to reference the host file first and the container destination second.

**Comment by alokedesai** [comment]
Hi @wzzrd, thank you so much for filing! I believe this was fixed by https://github.com/warpdotdev/workflows/pull/37 so going to mark as closed, but feel free to reopen if that's incorrect.

**Comment by elviskahoro** [comment]
@wzzrd if you're in our discord server what's your username so I can add the bug catcher role?

**Comment by wzzrd** [comment]
I am now :) It's wzzrd, just like here
