### ISSUE TITLE
Clarify workflow format

### ISSUE THREAD

**Issue by roeniss** [warpdotdev/Workflows#61]
Hi, at https://github.com/warpdotdev/workflows/blob/main/FORMAT.md#shells it said the `shell` field can be unspecified, but it can not be omitted:
```
...
shells: [] << this line must exist even though you don't specify single shell name.
...
```
shortly, "If not specified" can be interpreted in two ways: leave it as empty array or omit the field. I think it would be much helpful to point out the very first one.

Or, maybe we can provide a bolierplate workflow file which has only required fields.

**Comment by elviskahoro** [comment]
@roeniss did i already get your discord username? If not let me know, so I can add the Contributor discord role!

**Comment by elviskahoro** [comment]
@alokedesai I think you did this right?

**Comment by alokedesai** [comment]
Yes I believe this is done, please reopen if you feel that this is still confusing!
